name: chakra
description: "Chakra App"


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  hive: ^2.2.3
  fluttertoast: ^8.2.10
  validators: ^3.0.0
  flutter_svg: ^2.0.16
  cherry_toast: ^1.11.0
  flutter_spinkit: ^5.2.1
  change_app_package_name: ^1.4.0
  rename_app: ^1.6.1
  path_provider: ^2.1.5
  curved_navigation_bar: ^1.0.6
  date_picker_plus: ^4.1.0
  flutter_launcher_icons: ^0.14.2
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icons/chakra_app_icon.png"
  min_sdk_android: 21


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/icons/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Helvatica
      fonts:
        - asset: assets/fonts/Helvetica-Light.ttf
    - family: Techna
      fonts:
        - asset: assets/fonts/TechnaSans-Regular.otf
    - family: GothamBook
      fonts:
        - asset: assets/fonts/Gotham-Book.otf
    - family: GothamBold
      fonts:
        - asset: assets/fonts/Gotham-Bold.ttf
    - family: NotoSans
      fonts:
        - asset: assets/fonts/noto_sans.ttf

